version: '3.7'

services:
  rabbitmq3:
    image: rabbitmq:3-management
    restart: always
    ports:
     - "15672:15672"
     - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

